### ISSUE TITLE
[bug report] a minor logging bug in graphdot/kernel/marginalized/_kernel.py

### ISSUE THREAD

**Issue by hliuw** [yhtang/GraphDot#1]
It's a super minor bug so I think I may just report its instead of following the bug report

On the definition of _diag_ function in kernel on [this line](https://github.com/yhtang/GraphDot/blob/master/graphdot/kernel/marginalized/_kernel.py#L207), a timer is set as function argument to turn timer on/off. Then on [the begining line of this function](https://github.com/yhtang/GraphDot/blob/master/graphdot/kernel/marginalized/_kernel.py#L236), a timer is initialized regardless of the function argument, which, turn out to log unwanted information later in the [logging part](https://github.com/yhtang/GraphDot/blob/master/graphdot/kernel/marginalized/_kernel.py#L292)

We changed it in our local src code to avoid redundant logging and maybe a change in original code would be better

**Comment by yhtang** [comment]
Thanks for reporting! I fixed it in 72f369a295e0a40c3576dd81154e448303836cf7.
