### ISSUE TITLE
Some requirements are not installed when using `pip install graphdot`

### ISSUE THREAD

**Issue by jdagdelen** [yhtang/GraphDot#3]
I'm working on running graphdot in a Google Colab notebook. sing ```pip install graphdot``` does not install some of the required libraries that are called when running the example provided in the docs. These are:
* treelib
* rdkit (not pip-installable)

An example Colab with a working installation can be found here: 
https://colab.research.google.com/drive/1jNMRkUIbxzIJBqpaWgD-DTh4uuQE28Kb?usp=sharing

**Comment by yhtang** [comment]
Hi John,

Thanks for the feedback! I do not have permission to access the google drive file though. Could you please give me access?

Yu-Hang

**Comment by yhtang** [comment]
Fixed upstream.
